### ISSUE TITLE
Timeline - Messages

### ISSUE THREAD

**Issue by stefanceriu** [vector-im/element-x-ios#109]
As a user I would like to be able to see a particular room's timeline so that I can read my messages

- [x] Text message
- [x] Emote message
- [x] Notice message
- [x] Image message
- [ ] Video message
- [x] HTML support
- [x] Markdown support
- [x] Message bubble styling vector-im/element-x-ios/issues/34
- [x] Whitespace on bubbles vector-im/element-x-ios/issues/95
- [x] Message plain styling vector-im/element-x-ios/issues/92
- [x] Setting for switching styles vector-im/element-x-ios/issues/92

**Comment by stefanceriu** [comment]
Closing in favor of https://github.com/vector-im/element-x-ios/issues/237 and https://github.com/vector-im/element-x-ios/issues/238
