### ISSUE TITLE
Display emoji reactions

### ISSUE THREAD

**Issue by flescio** [vector-im/element-x-ios#783]
### Your use case

```[tasklist]
### Tasks
- [x] - Once an emoji has been added, a show more emoji icon next to the reaction is displayed (which will open the standard emoji set).
- [x] - The standard emoji set will have a selection state for the current users emojis
- [x] - Emoji added by the users will have a different state form the ones added by others (it will reflect the bubbles background)
- [x] - Reactions on messages received will be sticky to the left side
- [x] - Reactions on messages sent will be sticky to the right side
- [x] - If there are too many emoji introduce a 2nd row
- [x] - When there are more then 2 lines of emoji a pill will appear to expand / collpase those
```

- [x] QA signoff on completion
- [x] Design signoff on completion
- [x] Product signoff on completion

### Designs
- [Figma](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=2230-112976&t=YyUnPzEYKYD4bkVi-4)

### Rust Data
`timeline.rs EventTimelineItem.reactions()` will expose the reactions for a given event

### Dependency
[Expose more data in EventTimeline's Reactions](https://github.com/matrix-org/matrix-rust-sdk/issues/1792)

**Comment by langleyd** [comment]
https://github.com/vector-im/element-x-ios/pull/1158

**Comment by langleyd** [comment]
https://github.com/vector-im/element-x-ios/pull/1249

**Comment by langleyd** [comment]
Sorry, one of the checkboxes should not have been checked. The add more button will be added on iOS in https://github.com/vector-im/element-x-ios/pull/1314.

There are a few other discrepancies that will be cleaned up soon:

1. I think android should be filling the second row with emojis and adding he expand collapse as the end of the second row.
2. It's technically not possible to show the count on the expand button on iOS as it cause a bug that can freeze the app(an infinite loop where to get the count of those truncated we need to layout the view first -> Then update the count on the view -> which updates the layout -> loops forever). I want to review that with @callumu . It may also be an issue for android when they go to implement 1. and we may want to make the two consistent anyway with the "Show more" text.
3. The text color looks different across iOS/Android on the "Show more/less" button.

Will resolve these shortly, thanks @kittykat !

**Comment by langleyd** [comment]
@kittykat PR incoming here for the reaction order [here](https://github.com/vector-im/element-x-android/pull/912), and some other improvements that will bring it in line with iOS.

I have also started on the bottom sheet for reaction summary, that will probably come tomorrow.

So just an issue for the iOS jumping bug please.
